[package]
name = "murundiri"
version = "0.1.0"
authors = ["Tochukwu Nkemdilim <nkemdilimtochukwu@gmail.com>"]
edition = "2018"

[dependencies]
serde_yaml = "0.8.11"
serde = {version = "1.0.104", features = ["derive"] }
regex = "1.3.4"
